### ISSUE TITLE
[EPIC] Result recommendations

### ISSUE THREAD

**Issue by igor-sirotin** [six78/2-story-points-cli#44]
When votes are revealed, dealer (or everyone) should be provided with recommendations on final issue estimation.

As minimum, it should include a _median_ value of all votes.
But would be nice to make it smarter, e.g. detect a big diversity in votes and suggest revoting.

- [x] https://github.com/six78/2-story-points-cli/issues/51
- [x] https://github.com/six78/2-story-points-cli/issues/53
- [x] https://github.com/six78/2-story-points-cli/issues/57
- [x] https://github.com/six78/2-story-points-cli/issues/54
- [x] https://github.com/six78/2-story-points-cli/issues/55
- [x] https://github.com/six78/2-story-points-cli/issues/65
